[workspace]
resolver = "3"
members = ["wsn", "wsn-extract", "example", "wdll", ]

[profile.dev-no-panic]
inherits = "dev"
opt-level = 1
lto = "fat"
codegen-units = 1

[profile.test-no-panic]
inherits = "test"
opt-level = 1
lto = "fat"
codegen-units = 1

[profile.release-no-panic]
inherits = "release"
lto = "fat"
codegen-units = 1

[profile.dev-no-panic-no-std]
inherits = "dev-no-panic"
panic = "abort"

[profile.release-no-panic-no-std]
inherits = "release-no-panic"
panic = "abort"

[workspace.dependencies]
wsn = { path = "wsn", version = "0.1" }
wdll = { path = "wdll", version = "0.1" }
no-panic = "0.1"
anyhow = "1"
proc-macro2 = "1"
quote = "1"
csv = "1"
syn = "2"
prettyplease = "0.2"
clap = "4"
goblin = "0.10"
panic-never = "0.1"
widestring = { version = "1", default-features = false }
thiserror = { version = "2", default-features = false }