[workspace]
resolver = "3"
members = ["wsn", "wsn-extract", "example"]

[profile.dev]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[workspace.dependencies]
no-panic = "0.1"
anyhow = "1"
proc-macro2 = "1"
quote = "1"
csv = "1"
syn = "2"
prettyplease = "0.2"
clap = "4"
goblin = "0.10"
panic-never = "0.1"
