[package]
name = "wsn-extract"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/BrainStackOverFlow/wsn"
license-file = "../LICENSE"
description = "CLI for Extracting Windows Syscalls Numbers from ntdll"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
goblin = { workspace = true }