[package]
name = "wsn"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/BrainStackOverFlow/wsn"
license-file = "../LICENSE"
keywords = ["no-std", "no-panic"]
description = "no-std no-panic Windows Syscalls Numbers library"

[dependencies]
no-panic = { workspace = true, optional = true }
wdll = {workspace = true, optional = true}

[features]
no-panic = ["dep:no-panic", "wdll?/no-panic"]
wdll = ["dep:wdll"]

[build-dependencies]
anyhow.workspace = true
proc-macro2.workspace = true
quote.workspace = true
csv.workspace = true
syn.workspace = true
prettyplease.workspace = true
